version: "3.9"
services:
  # ---------------------
  # Databases
  # ---------------------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: omnistack
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - ../../data/pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../../data/mongodata:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # ---------------------
  # Messaging
  # ---------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

  # ---------------------
  # Identity Provider
  # ---------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../../data/keycloakdata:/opt/keycloak/data
  # ---------------------
  # Monitoring
  # ---------------------
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # ---------------------
  # Logging - Splunk
  # ---------------------
  splunk:
    image: splunk/splunk:9.2.1
    container_name: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: changeme123
      SPLUNK_USERNAME: admin
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC
      - "9997:9997"   # Indexer
    volumes:
      - ../../data/splunk-data:/opt/splunk/var

  fluentd:
    build: ./logging
    container_name: fluentd
    depends_on:
      - splunk
    volumes:
      - ./logging/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      
  auth-service:
    # build:
    #   context: ./services/auth
    image: ishanthakur1998/omnistack-auth-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/omnistack
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: omnistack
      KEYCLOAK_CLIENT_ID: auth-service-admin
      KEYCLOAK_CLIENT_SECRET: PwHYPwuf3nVlWOVUTtmN0RL4Gsx18LWz
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - keycloak

